### ISSUE TITLE
'executive' package not found

### ISSUE THREAD

**Issue by astro-rizki** [nasa/astrobee#12]
i'm trying to simulate astrobee in VMWare, the rviz and sviz was showed up perfectly but when I try to send a command to undock, I came up with this error 
`[rospack] Error: package 'executive' not found`

<img width="802" alt="executive not found" src="https://user-images.githubusercontent.com/34902434/68557413-4ccf8600-0468-11ea-8aaf-33bf33c89fb2.PNG">

**Comment by kbrowne15** [comment]
Did you source the Astrobee setup in that terminal? Please see the Setting up your Environment section of https://github.com/nasa/astrobee/blob/master/sim_overview.md on how to do this. As stated in the documentation, you must do this in every terminal that you call the teleop tool from.
