### ISSUE TITLE
I've Installed Ubuntu...Now What? 

### ISSUE THREAD

**Issue by Sol-Rover** [nasa/astrobee#13]
I've installed the version of Ubuntu that is required for this project but I'm not really sure how to do the next steps. How exactly do I clone the repositories? Am I supposed to download additional software, in addition to the OS? If so, what else do I need to install? Thank you so much in advance for any responses. I apologize for causing any inconvenience. I'm new to this sort of thing and want to understand it. Again, thank you to anyone who responds! I really appreciate it.

**Comment by papino0319** [comment]
Hi, Sol-Rover, 
You can find additional information at [Usage instructions for non-NASA users](https://github.com/nasa/astrobee/blob/master/INSTALL.md)
