### ISSUE TITLE
Sparse Mapping Orientations Displayed in Gviz Incorrect

### ISSUE THREAD

**Issue by bcoltin** [nasa/astrobee#145]
In the last activity, gviz sparse mapping updates were showing orientation estimates inconsistent with the pose estimate. However, the pose seemed correct in GDS and the robot was moving fine. We suspect there may be a bug in displaying the orientations of sparse map poses in gviz.

**Comment by trey0** [comment]
This issue relates to:
- ISS activity: Crew-Minimal 11
- Date: 2021/03/10
- FSW release: 0.14.1

**Comment by bcoltin** [comment]
This hasn't been reported recently. We believe an old version of gviz was used.
