### ISSUE TITLE
Localization Not Integrating Sparse Map Features?

### ISSUE THREAD

**Issue by bcoltin** [nasa/astrobee#148]
During the activity, gviz would frequently show sparse map poses. However, it was not showing sparse map features being integrated into localization. What is happening?

**Comment by trey0** [comment]
This issue relates to:
- ISS activity: Crew-Minimal 11
- Date: 2021/03/10
- FSW release: 0.14.1

**Comment by bcoltin** [comment]
Could not reproduce. However, during the testing there were large areas with no sparse map features.
