### ISSUE TITLE
Add pico proxy to the ISAAC launchfile

### ISSUE THREAD

**Issue by bcoltin** [nasa/astrobee#158]

**Comment by oleg-alexandrov** [comment]
Actually this should even be in the astrobee repo as well. If the haz cam is meant to take pictures, it should as well decode properly the depth right away. We need to do that for ISS work, and I don't know if we will ever install isaac on the ISS. Having pico_proxy only for isaac looks of limited value to me.

**Comment by bcoltin** [comment]
ISAAC is already installed on the ISS. I don't think the obstacle detection requires pico_proxy, so the default Astrobee software doesn't need it?

**Comment by oleg-alexandrov** [comment]
I am not sure what the default astrobee software does with the depth camera.

**Comment by marinagmoreira** [comment]
This was done in the latest ISAAC release for the ISAAC3 activity. This was tested in the lab and in space
