### ISSUE TITLE
I have problem sim.launch

### ISSUE THREAD

**Issue by ToonKru3** [nasa/astrobee#18]
***@ubuntu:~$ roslaunch astrobee sim.launch dds:=false robot:=sim_pub rviz:=true

**[sim.launch] is neither a launch file in package [astrobee] nor is [astrobee] a launch file name
The traceback for the exception was written to the log file**

**Comment by bcoltin** [comment]
You need to source the setup.bash file after you build the software. See the instructions here: https://github.com/nasa/astrobee/blob/master/simulation/sim_overview.md
