### ISSUE TITLE
Update all python2 scripts to python3

### ISSUE THREAD

**Issue by marinagmoreira** [nasa/astrobee#200]
Should not be too hard if we use the 2to3 tool (for the spawn_model, the tool converted it automatically with zero issues).
This is needed given the recent ubuntu 20 compatibility

**Comment by trey0** [comment]
Yeah, I agreee the cleanest approach is to port everything to Python 3 and run that way on all distros, rather than figure out how to install obsolete Python 2 on Ubuntu 20.04 (although that wouldn't be too hard either).

**Comment by bcoltin** [comment]
Only potential issue is anything that needs to run on the robot. (not sure there is anything)

I believe that ROAM used python3 on the robot so I think this is fine but will need to check.
