### ISSUE TITLE
Start pico_proxy by default

### ISSUE THREAD

**Issue by bcoltin** [nasa/astrobee#234]
Currently it is a separate step in the procedure. Let's start this automatically, but make sure it only publishes if there are subscribers, and it behaves gracefully without the api key and with no inputs.

**Comment by marinagmoreira** [comment]
This is what we currently have on the isaac fsw:    


    <arg name="topic" default="/hw/depth_haz/extended"/>
    <arg name="topic_type" default="extended"/>
    <arg name="amplitude_factor" default="100.0"/>
    <node name="$(anon pico_proxy)" pkg="pico_driver" type="pico_proxy" output="screen">
      <param name="topic" type="string" value="$(arg topic)"/>
      <param name="topic_type" type="string" value="$(arg topic_type)"/>
      <param name="amplitude_factor" type="double" value="$(arg amplitude_factor)"/>
    </node>
