### ISSUE TITLE
Support for 20.04

### ISSUE THREAD

**Issue by ana-GT** [nasa/astrobee#263]
This is not really an issue, but it is more a question: Is there any plan for supporting or at least testing if the Astrobee software works in Ubuntu 20.04/ROS Noetic? We are currently running our astrobees simulation in 18.04 (working very well!), but since for other projects we have effectively switched to 20.04, we were wondering if there might be the possibility for Astrobee to run in 20.04 at some point. If I remember right, I think I was able to compile the astrobee software (develop branch) in 20.04 some weeks back, but I didn't manage to run things.

Thanks!

**Comment by bcoltin** [comment]
Hi Ana,

Yes, we very recently added support for 20.04! You should be able to use the same instructions and the scripts will automatically detect the OS version and configure things appropriately. Let us know if you run into any trouble!
