### ISSUE TITLE
Pan/Tilt command failed to stow arm

### ISSUE THREAD

**Issue by kbrowne15** [nasa/astrobee#268]
This occurred during the Astroporter activity on 8/26/21. After a quick lab test, we believe it was because the gripper wasn't calibrated. Discuss at fsw meeting on 8/30.

**Comment by bcoltin** [comment]
Need to add unstow arm command.

**Comment by kbrowne15** [comment]
Fixed in https://github.com/nasa/astrobee/pull/482#event-6517017886
