### ISSUE TITLE
Arm failed to deploy during perching

### ISSUE THREAD

**Issue by kbrowne15** [nasa/astrobee#274]
During the CM on 09/1/21, the arm failed to deploy during perching. Unfortunately the arm behavior topics weren't part of the perching recording profile used during the activity. However, there may be error output in the log files/rosout topic. Steps moving forward are to analyze the data from the CM once it is downloaded, try to recreate the failure in the granite lab, and add the arm topics to the perching recording profile.

**Comment by bcoltin** [comment]
Need to add arm topics to default recording profile.

**Comment by bcoltin** [comment]
@kbrowne15 did we do this?

**Comment by kbrowne15** [comment]
Just added the arm topics to the perching recording profile in the ops repo.
