### ISSUE TITLE
Remove disabling the obstacle detection in the startup plan

### ISSUE THREAD

**Issue by kbrowne15** [nasa/astrobee#279]
Need to discuss with Jonathan if they are going to use this more often or if we want to test it during a CM. Based on this, we may need to remove the set check obstacle to false command in the startup plan.

**Comment by bcoltin** [comment]
@kbrowne15 any update on this?

**Comment by kbrowne15** [comment]
We are still testing this in CMs and it will probably be quite a while if at all before we actually turn obstacle detection on for good. Should we close this issue for now?

**Comment by bcoltin** [comment]
Sure sounds good.
