### ISSUE TITLE
Create Automatic Startup Script

### ISSUE THREAD

**Issue by bcoltin** [nasa/astrobee#283]
Try to automate tasks the facility has to do manually, such as checking and setting the time, running startup plan, adding picoflexx api key, etc.

**Comment by bcoltin** [comment]
@kbrowne15 can we close this, with your picoflex script and Ruben's gds tools?

**Comment by kbrowne15** [comment]
Yes, there might be more minor startup scripts that we need to make but that can be done as we go.
