### ISSUE TITLE
Simulation of acoustic/RFID sensors?

### ISSUE THREAD

**Issue by ana-GT** [nasa/astrobee#30]
Hi. Just wondering if there are some plans to add plugins for simulating RFID/acousting sensors in the Gazebo simulation. I took a look at the xacro files and don't seem to find a reference. Thank you very much!

**Comment by bcoltin** [comment]
Hi Ana,

We have a plugin for the acoustics sensors and will likely need to make one for the RFID soon. However we do not have approval to release it open source and it may be a while until we do (it is under a different project). Do you have a NDC account through JSC? If so we could get you access to it.

**Comment by bcoltin** [comment]
(send me an email)
