### ISSUE TITLE
The doc appears to have a minor inacuracy

### ISSUE THREAD

**Issue by oleg-alexandrov** [nasa/astrobee#309]
I followed the instructions at:

   https://github.com/nasa/astrobee/blob/develop/doc/general_documentation/INSTALL.md

./src/scripts/configure.sh -l -F -D -p $INSTALL_PATH -b $BUILD_PATH

I get the error:

./scripts/configure.sh: illegal option -- b

It appears that this option was changed and the doc was not updated. There's like more than one place where this shows up.

**Comment by marinagmoreira** [comment]
thanks for reporting this, instead of -b we now have -w for the location of the workspace.
