### ISSUE TITLE
Arm command dictionary does not match the robot

### ISSUE THREAD

**Issue by jsbarlo** [nasa/astrobee#310]
Under Arm.armPanAndTilt in the command dictionary https://github.com/nasa/astrobee/wiki/Command-Dictionary#command_Arm.gripperControl, the range of the arm tilt is listed as -30 <= val <= 90 values between -30 and -20 give an error
![Screen Shot 2021-11-01 at 11 17 22 AM](https://user-images.githubusercontent.com/85182932/139720683-b9fdb295-85ed-4b66-aa60-5a40dc908436.png)
![Screen Shot 2021-11-01 at 11 10 41 AM](https://user-images.githubusercontent.com/85182932/139720687-93d34ea1-743a-4a83-b42f-ac15dc121567.png)
.

**Comment by trey0** [comment]
The canonical location of the command dictionary is [1], which appears to be correct. Not sure where that wiki page came from?

[1] https://nasa.github.io/astrobee/html/command_dictionary.html#command_Arm.armPanAndTilt

**Comment by bcoltin** [comment]
We will delete the wiki.

**Comment by marinagmoreira** [comment]
wiki deleted with link to actual documentation
