### ISSUE TITLE
Merge bag tools into one

### ISSUE THREAD

**Issue by marinagmoreira** [nasa/astrobee#329]
There is currently 2 merge bag tools in astrobee/tools/graph_bag/scripts/merge_bags.py and astrobee/localization/localization_node/tools/merge_bags.cc.

The functionality of both should be merged into the c++ api one (because the python api crashes with messages from rosjava) and moved to the astrobee/tools folder for better visibility of users

**Comment by bcoltin** [comment]
@rsoussan this isn't super urgent, but do you use tools/graph_bag/scripts/merge_bags.py? What does this have that astrobee/localization/localization_node/tools/merge_bags.cc lacks?

**Comment by rsoussan** [comment]
It automatically finds bags with a given prefix in a directory and merges them, and adds an option to only save localization topics to keep the bags smaller.

**Comment by bcoltin** [comment]
We'll move all the bag processing scripts from both locations into a new ros package in tools.

**Comment by bcoltin** [comment]
We think the python script does everything and we can now delete the C++ script. However, let's wait a bit to make sure we still don't need it.

**Comment by bcoltin** [comment]
@marinagmoreira will add a warning to the C++ version that it is obsolete.

**Comment by marinagmoreira** [comment]
Also merged both python merge scripts into one, that can merge entire directory or selected files

**Comment by bcoltin** [comment]
Will call the C++ script from python and get rid of the duplicate functionality in the python script.
