### ISSUE TITLE
graph_localizer is missing teaserpp deps in 16.0

### ISSUE THREAD

**Issue by albee** [nasa/astrobee#385]
The 16.0 release of graph_localizer is missing teaserpp dependency statements in the CMakeLists.txt that is causing the nodelet to crash in simulation. See screenshot below. (Ryan and I saw a similar issue on hardware that we managed to fix by adding a few target_link_libraries statements and catkin dependencies for teaserpp.)

Wanted to make sure this wasn't just me, if so then I don't think the sim will work for anyone with the current release. I can do a PR if needed.

![image](https://user-images.githubusercontent.com/5566617/148124695-21392499-e6c3-4327-b4a0-f091d6e72dc4.png)

**Comment by albee** [comment]
I've fixed this locally by the way by adding the deps back in to the CMakeLists.txt.

**Comment by rsoussan** [comment]
Which dependencies fixed the issue?  I'll test sim on my laptop, although I think I did before the main Depth Odom pr which is currently on dev.

**Comment by bcoltin** [comment]
Seems like this is just Keenan and he fixed it. If that's not the case please re-open.
