### ISSUE TITLE
Debayer colors not matching reality + make decoding tool

### ISSUE THREAD

**Issue by marinagmoreira** [nasa/astrobee#420]
The debayer node is producing images that have switched colors, so we should look into it (on iss images red->blue).

Previous efforts on this end tested all the possibilities in: http://docs.ros.org/en/diamondback/api/image_proc/html/debayer_8cpp_source.html line 95-110 and the chosen one was what matched reality best (https://github.com/nasa/astrobee/pull/270/files).

A decoding tool should be made to easily process the bagfiles

Actions:
- [x] Figure out the correct encoding
- [x] Make tool to debayer color image
- [x] Make tool to debayer mono image the same way as it is done for fsw

**Comment by marinagmoreira** [comment]
@rsoussan @bcoltin

**Comment by bcoltin** [comment]
In progress.
