### ISSUE TITLE
Intermittent Heartbeat Faults for Mapper 

### ISSUE THREAD

**Issue by kbrowne15** [nasa/astrobee#421]
During the SVGS activity on 2/16/22, the heartbeat for the mapper was thrown when Astrobee faced the airlock from bay 5 towards the end of the activity. This issue is new since adding the nice argument. Need to investigate if the mapper is significantly struggling and needs to be fixed or if the heartbeat trigger is too short for the mapper. Currently the system monitor throws a heartbeat fault if it doesn't receive a mapper heartbeat in 2 seconds.

**Comment by bcoltin** [comment]
We are disabling the mapper until we fix this.
