### ISSUE TITLE
Change bayer encoding

### ISSUE THREAD

**Issue by marinagmoreira** [nasa/astrobee#434]
The correct bayer encoding is actually bayer_grbg8. We will change the bayer image encoding in the ros message but not the mono camera decoding given that the maps are dependent on it.

Image printed:
![20651236](https://user-images.githubusercontent.com/67443181/156644099-434a5cf8-ba46-48e4-a026-97254622b758.jpg)
Decoded bayer image using the encoding bayer_grbg8 (using image_proc package https://github.com/ros-perception/image_pipeline/blob/71d537a50bf4e7769af513f4a3d3df0d188cfa05/image_proc/src/nodelets/debayer.cpp#L226).
![Screenshot from 2022-03-03 10-35-20](https://user-images.githubusercontent.com/67443181/156644139-be7a5f72-fecc-4f2f-b0e8-1794bed8285e.png)

**Comment by trey0** [comment]
Hi, Marina- In your issue description, could you just briefly document how the attached images support your analysis of the bayer encoding? (What are they showing? How was the bottom color image generated?)
