### ISSUE TITLE
Astrobee 3-DOF Compliant Perching Arm

### ISSUE THREAD

**Issue by shiba-8ro** [nasa/astrobee#495]
Hi, My simple question.
Will Astrobee 3-DOF Compliant Perching Arm data be open source?

**Comment by shiba-8ro** [comment]
Thank you for your reply.
Can we use 3D-Printable data? For example, STL.

**Comment by bcoltin** [comment]
Sorry, we are unable to share the STL files.

**Comment by shiba-8ro** [comment]
I understood. Thank you for reply.
