### ISSUE TITLE
debuild doesn't fully use all cores when 'catkin build'

### ISSUE THREAD

**Issue by marinagmoreira** [nasa/astrobee#497]
Without all cores being fully used debian build is really slow.

Current workaround for this is to:
1) start debuild for catkin configs
2) stop it when it starts compiling
3) do 'catkin clean' do delete previous debian build
4) do 'catkin build' (directly issuing a catkin build uses all available resources, which is much faster), wait for completion
5) re-run debuild to completion (it will use the previous build instead of doing everything from scratch)

**Comment by bcoltin** [comment]
We don't know how to fix this. We will continue using Marina's workaround.
