### ISSUE TITLE
Handrail Detection New Approach

### ISSUE THREAD

**Issue by Aryan-Naveen** [nasa/astrobee#530]
[https://github.com/Aryan-Naveen/astrobee-handrail-detection](url)

This fork contains the code for handrail detection using a Mask RCNN model. The package is located inside localization/handrail_segmentation. Note that also the world file in ignition gazebo is included as well as the plugin used to generate data in case that can be of use.

**Comment by bcoltin** [comment]
Used in Morgan's intern project
