### ISSUE TITLE
Migrate CI workflows to Ubuntu 20.04 runner image (18.04 deprecated)

### ISSUE THREAD

**Issue by trey0** [nasa/astrobee#550]
[GitHub is deprecating Ubuntu 18.04 runner images in CI workflows](https://github.com/actions/runner-images/issues/6002).

We should change our CI workflows replacing `runs-on: ubuntu-18.04` -> `runs-on: ubuntu-20.04`, for example in [this workflow](https://github.com/nasa/astrobee/blob/master/.github/workflows/ci_push.yml).

This won’t affect our ability to continue supporting multiple Ubuntu versions in Astrobee FSW. It only controls the Ubuntu version of the runner image used to build the Docker container, not the Ubuntu version inside the container.

**Comment by marinagmoreira** [comment]
Action: [Build and Push Documentation to gh-pages Branch](https://github.com/nasa/astrobee/actions/workflows/docs.yaml)
* now fails at the "generating command dictionary documentation" step, we'll have to put this inside a docker image given that upgrading xgds is not in scope
