### ISSUE TITLE
Remove unused file? ground_dds_ros_bridge/nodelet_plugins.xml

### ISSUE THREAD

**Issue by trey0** [nasa/astrobee#558]
The file [ground_dds_ros_bridge/nodelet_plugins.xml](https://github.com/nasa/astrobee/blob/master/communications/ground_dds_ros_bridge/nodelet_plugins.xml) looks like it is an accidental leftover from copying a whole folder. This package doesn't actually define a plugin.

**Comment by kbrowne15** [comment]
Fixed in pr https://github.com/nasa/astrobee/pull/560
