### ISSUE TITLE
Improve make_surf_map.py's image path handling

### ISSUE THREAD

**Issue by amoravargas** [nasa/astrobee#578]
Script [make_surf_map.py](https://github.com/nasa/astrobee/blob/master/localization/sparse_mapping/scripts/make_surf_map.py) always uses the bag name to generate folder containing treated images.
Improve by providing ability to generate folder at given path. 
This is important as it facilitates data organization when building maps. @rsoussan

**Comment by marinagmoreira** [comment]
@amoravargas confirmed that this was solved
