### ISSUE TITLE
Freeflyer Sensor Plugins with embedded names

### ISSUE THREAD

**Issue by marinagmoreira** [nasa/astrobee#59]
Right now, the way the class FreeFlyerSensorPlugin is build, the name of the node is embedded, which means that each plugin can only be spawned once. This causes some trouble as multiple plugin codes are necessary just to change the name (e.g. right and left flashlight are different plugins).

**Comment by bcoltin** [comment]
Not sure if there is an easy solution. Marina will look into it and talk to Brian about it.

**Comment by bcoltin** [comment]
We will try changing freeflyernodelet so it can accept the nodelet name outside the constructor, then set it when reading the configuration file.
