### ISSUE TITLE
Clock in ROS2

### ISSUE THREAD

**Issue by marinagmoreira** [nasa/astrobee#613]
This is another case using a macro that looks different from the idiomatic ROS2 API call, which I guess would be `node->getClock()->now()` (meaning you need to have the node pointer handy).

If the definition of `ROS_TIME_NOW()` is similar to the example in `ros_compat.h`, it's mildly concerning. Their `ROS_CREATE_NODE()` macro defines its own private global clock object to be used by future `ROS_TIME_NOW()` calls. This defeats the ROS2 concept, as I understand it, that each node has its own clock. I'm not clear how important that compartmentalization is, but if ROS2 supports running multiple nodes in the same process, it might be important to use the clock from the right node (e.g., some nodes might have their clocks initialized before others).

I think the namespaced inline function approach can't provide a definition that looks exactly like the ROS2 API call since the API involves a member function, but if we relax the requirement to match the syntax exactly, at least it could provide an inline function `ff_ros::now(node)` implemented as:
- ROS1: `ros::Time::now()` (ignoring the node argument)
- ROS2: `node->getClock()->now()`

Or we could decide to just stick with a macro for now, at the risk of having unexpected hassles later.

But if we are using macros for ROS abstraction, they should have a standard prefix such as `FF_ROS`...

_Originally posted by @trey0 in https://github.com/nasa/astrobee/pull/600#discussion_r1037419941_

**Comment by bcoltin** [comment]
We could also just have the time be different in ros1 and ros2 branches. It isn't very hard to merge and convert between the two here.

Also, now() is what we use most of the time, so maybe this is worthwhile, but for anything more complicated the underlying data type has changed so we won't be able to use the same code in both versions unless we really want to expand our macro library.
