### ISSUE TITLE
Docker File potential error

### ISSUE THREAD

**Issue by viraj96** [nasa/astrobee#62]
Hi I was having a look at the docker file provided for Ubuntu18 and while doing that I found that the astrobee_init.sh file created depends on ROS Kinetic instead of Melodic. This is evident [here](https://github.com/nasa/astrobee/blob/bb0fc3e4110a14929bd4cf35c12b3c169bc6c756/scripts/docker/Dockerfile_astrobee18#L122). I think it should have been melodic.

**Comment by marinagmoreira** [comment]
Hi! Thanks for reporting, but it seems like this is already corrected in the develop version:
https://github.com/nasa/astrobee/blob/e74a3f407c043f2c879015e81b316867739fa4bd/scripts/docker/astrobee_base_melodic.Dockerfile#L114
