### ISSUE TITLE
ROS2: store a node_ variable instead of clock_

### ISSUE THREAD

**Issue by marinagmoreira** [nasa/astrobee#639]
Yeah it was one of the things that I didn't have a preference for and chose randomly whether to store a node_ variable or clock_ variable :)

_Originally posted by @marinagmoreira in https://github.com/nasa/astrobee/pull/633#discussion_r1072726121_

**Comment by bcoltin** [comment]
Define node_ on astrobee plugin / component classes as protected variables so we don't have to declare it in every class. Make a class variable to get time instead of macro
