### ISSUE TITLE
Verify that map coverage analysis tools work under Python 3

### ISSUE THREAD

**Issue by trey0** [nasa/astrobee#681]
@amoravargas wrote coverage analysis tools in `scripts/postprocessing/coverage_analysis`. The task is to verify they work and produce valid output when migrated to run under Ubuntu 20.04 (with ROS Noetic and Python 3). The rationale is that this would allow @amoravargas to run his coverage analyses under Ubuntu 20.04, which in turn would allow us to upgrade the astrobeast server he uses from 18.04 to 20.04 and get us one step closer to discontinuing support for Astrobee development under 18.04.

The relevant scripts are:

- [ ] `activity_db_generator.py`
- [ ] `coverage_analyzer.py`
- [ ] `coverage_painter.py`
- [ ] `coverage_stats_reporter.py`
- [ ] `img_to_bag.py`

Here is the progress so far:
- `activity_db_generator.py`: Run under Ubuntu 20.04, it ran without errors and produced well-formed output, but the output was not the same as under Ubuntu 18.04. Further investigation revealed that, when run according to the provided instructions, the output is not repeatable from run to run on either platform. This is not the fault of the script itself, but rather, the upstream nodes (bag playback plus localization nodes) produce variable output when the bag playback is run at 1:1 real-time speed because the localization nodes saturate and drop images they can't process in real-time. I would argue this is a serious problem to fix to improve the analysis, but not relevant to the migration task at hand (except that it hinders output validation in this case).
- `coverage_analyzer.py`: Run under Ubuntu 20.04, it ran without errors and produced well-formed output, but the output was not the same as under Ubuntu 18.04. Required changes in #680. After that, it produced identical output in the provided real-world test case.
- `coverage_painter.py`: It ran under Ubuntu 20.04 without errors. I found it hard to verify identical output for boring reasons (its output is messages published for RViz, which doesn't work well on my laptop). However, what it does is pretty straightforward, and I have no reason to suspect the output would be different.
- `coverage_stats_reporter.py`: Run under Ubuntu 20.04, it ran without errors, and the PDF output was visually the same as under Ubuntu 18.04.
- `img_to_bag.py`: Run under Ubuntu 20.04, it ran without errors and produced well-formed output. I didn't have a great way to check the binary output was semantically identical (it is a binary file that is not expected to be byte-identical), but again the code is pretty straightforward with no reason to suspect the output would differ semantically.

My recommendation would be to close this task after #680 is merged and declare success such that astrobeast can be upgraded. But I wanted to document the limitations of the verification I did for @amoravargas and get buy-in that we are ready.

**Comment by amoravargas** [comment]
Thanks for the verification and feedback. I'm ok with your recommendation.
