### ISSUE TITLE
Improve is_camera thread safety

### ISSUE THREAD

**Issue by trey0** [nasa/astrobee#722]
#689 proposed some changes to improve `is_camera`, but as submitted caused a crash on startup when auto-exposure was enabled, and we had limited capability to debug why that was happening. Probably the concepts behind the changes were fine, but there was a subtle error in the implementation which we haven't been able to track down yet.

@marinagmoreira - I think you may have cherry-picked some of the changes from #689 and applied them separately to `develop`, but that didn't include the thread safety improvements. Could you clarify a bit the current state?

**Comment by marinagmoreira** [comment]
Yup, I merged this in: https://github.com/nasa/astrobee/commit/825a0401cdf1e63be6ccd2cab1506146f1534b60
So only that indexing bug was fixed
