### ISSUE TITLE
Exposure change crashes localizer sometimes

### ISSUE THREAD

**Issue by marinagmoreira** [nasa/astrobee#810]
when changing the exposure like so:
`/opt/astrobee/ops/gds/isaac_scripts/nav_exposure.bash set 300`
the localization node crashes in a non deterministic way. This is because it reads from the config file when it is re-written.
Changing the exposure through the service works well and doesn't crash anything.

This is the timer that gets triggered when changing the file:
https://github.com/nasa/astrobee/blob/master/localization/localization_node/src/localization_nodelet.cc#L120

**Comment by kbrowne15** [comment]
Since a command has been added to set exposure, it is no longer nominal process to set the camera exposure by changing the config file while software is running. Thus, this issue is being marked as a won't do and it is highly recommend that the set exposure command is used instead.
